TRAPDOOR_GPIO_PIN = 12
TRAPDOOR_CLOSED_ANGLE = 10
TRAPDOOR_OPEN_ANGLE = 90

TRAIN_GPIO_PIN = 13
TRAIN_POSIION_A = 10
TRAIN_POSIION_B = 90
TRAIN_POSIION_C = 170

MOTOR_GPIO_PIN = 25
MOTOR_SLOW_PWM = 15
MOTOR_HIGH_PWM = 100
MOTOR_START_DURATION = 0.75
