TRAPDOOR_GPIO_PIN = 12
TRAPDOOR_CLOSED_ANGLE = 10
TRAPDOOR_OPEN_ANGLE = 90

TRAIN_GPIO_PIN = 13
TRAIN_POSIION_A = 10
TRAIN_POSIION_B = 90
TRAIN_POSIION_C = 170

CARRIER_GPIO_PIN = 6
CARRIER_CENTER_ANGLE = 90
CARRIER_EXTENT = 90
CARRIER_SWEEP_DURATION = 0.5
CARRIER_WAIT_TIME = 0.3
